// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Food struct {
	ID        int32
	Name      string
	Price     string
	FoodImage string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	FoodID    uuid.UUID
	MenuID    uuid.UUID
}
